name: simple_tip
version: 0.3.1
description: >-
  A widget for showing tips to it's child that automatically setup position
repository: https://github.com/evan361425/flutter-simple-tip

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
